### ISSUE TITLE
Show a backspace button

### ISSUE THREAD

**Issue by rocboronat** [Fintasys/emoji_picker_flutter#10]

**Comment by Fintasys** [comment]
Thank you for your suggestion ! Any suggestion where? Whatsapp has an extra row below the smilies with a backspace button.

**Comment by rocboronat** [comment]
I've tried on an iPhone and it shows the backspace at the end of the category list, and the categories appear below the emoji list instead of above. And it looks cool 👍 

In the Android native app we used [vanniktech/Emoji](https://github.com/vanniktech/Emoji) and they chose to show a backspace button in the category list. It doesn't look great, but it's usable I think. The categories are above the emojis, too. It looks like this:

![NativeQuitNow](https://user-images.githubusercontent.com/456499/118050610-e50d3a80-b37f-11eb-93cd-d83328b3e86f.jpg)

If I could choose, I would mimic what the native iOS keyboard does 😅 

Thanks a lot for taking a look to the issue, @Fintasys !

**Comment by Fintasys** [comment]
@rocboronat I've released 1.0.5 with font-size fix and backspace-button. Please have a look and let me know if it works !
![backspace](https://user-images.githubusercontent.com/11667234/118302614-67803080-b51f-11eb-988b-f2dc0e229b5c.png)

**Comment by rocboronat** [comment]
Oh my god! Thanks a lot, @Fintasys ! 👌

**Comment by rocboronat** [comment]
Tested with 1.0.5 and it works like a charm 👏 thanks!
