### ISSUE TITLE
Config progressIndicatorColor dismiss

### ISSUE THREAD

**Issue by anchao-lu** [Fintasys/emoji_picker_flutter#111]
on v1.4.0 Config progressIndicatorColor dismiss

**Comment by Fintasys** [comment]
@anchao-lu Sorry can you give more details? I'm having trouble understanding what's your issue 🙇

**Comment by nitesh2599** [comment]
@Fintasys In 1.4.0 release, `progressIndicatorColor` was removed rom `Config` class, which is a breaking change.

**Comment by Fintasys** [comment]
Oh right, seems I forgot to mention that in change log.
`progressIndicatorColor` was removed in the favor of `loadingIndicator` Widget so that we can provide more customize loading experience. But the speed increased significantly so that by default no LoadingIndicator is necessary.
