### ISSUE TITLE
[QUESTION] How to clear the recent emoji list ?

### ISSUE THREAD

**Issue by Nico3652** [Fintasys/emoji_picker_flutter#115]
Everything is in the title, I would like to clear the recent emoji list manually.
 It is possible in the current version ? 

I have noticed you stored the list in shared preference but I also have a lot of data inside so I can't clear the pref. 

Thanks for answers

**Comment by Fintasys** [comment]
Method `clearRecentEmojis` was added to `EmojiPickerUtils` 👍 Please update your app to `1.5.1` to use it.
