### ISSUE TITLE
Emojis break in flutter web when the page-width is below a certain width

### ISSUE THREAD

**Issue by Cellaryllis** [Fintasys/emoji_picker_flutter#123]
When scaling the page width of the flutter app down to a small width the emojis will fail to render.
See video for example

https://user-images.githubusercontent.com/95936504/215329547-898fdca3-f346-4d1a-b7e4-0c25a4ce8790.mp4

In case it is relevant: Reproduced in Firefox browser.

**Comment by Fintasys** [comment]
@Cellaryllis Seems rendering emoji is difficult at certain size. I would recommend you to adjust row and columns according to width of the screen to ensure they are displayed correctly.

**Comment by Fintasys** [comment]
Please have a look at this PR. If there is anything else please open a new Issue 🙏
