### ISSUE TITLE
Emoji are not rendered properly in web on flutter 2.7

### ISSUE THREAD

**Issue by tahaJemmali** [Fintasys/emoji_picker_flutter#124]
![image](https://user-images.githubusercontent.com/49129221/215408212-24aefbdf-c021-4a6c-ac34-48a499ec05a0.png)

**Comment by thomas4Bitcraft** [comment]
@tahaJemmali Same for me. Did you find a solution for this problem?

**Comment by mirkancal** [comment]
Same in 3.7.3.

**Comment by tahaJemmali** [comment]
@thomas4Bitcraft I reverted back to the old version of flutter :

[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [version 10.0.22000.1574], locale en-US)
    • Flutter version 3.3.9 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

**Comment by Fintasys** [comment]
I agree, I think the issue is Flutter related. If you still think it's relates to the package it would be nice if you could provide some example code.

**Comment by tahaJemmali** [comment]
No it's not related to the package, I'm going to close the issue. 
Ps: thank you for the package, very helpfull !

**Comment by LostInDarkMath** [comment]
See also https://github.com/flutter/flutter/issues/119536
