### ISSUE TITLE
Issue on adding emoji between emojis

### ISSUE THREAD

**Issue by devbrisk** [Fintasys/emoji_picker_flutter#125]
There is an issue when I want to insert emoji between inserted emojis.
Insert emoji between text is ok but between emojis has issue.
After inserting emoji, text will be converted to a single character like this:

![Screenshot_1](https://user-images.githubusercontent.com/114703704/216789100-ffd1918e-8ece-4e01-b9f7-e3b28be2ae7a.jpg)

**Comment by Fintasys** [comment]
@devbrisk I can't replicate the issue with the example. Could you provide an example to check?

**Comment by devbrisk** [comment]
You can see the example in the following :
https://github.com/Fintasys/emoji_picker_flutter/assets/114703704/e2c3ab9d-fa51-47cb-a095-5e13b4720143

**Comment by Fintasys** [comment]
@devbrisk Sorry but it seems to be an issue within your implementation. I tried to replicate the issue with example project but I couldn't reproduce it. If you can provide a minimal example where you can reproduce the issue I would look into it.
