### ISSUE TITLE
Unable to switch emoji panel and keyboard!

### ISSUE THREAD

**Issue by luohao123** [Fintasys/emoji_picker_flutter#133]
I an using `onTap` for textfield to make it switch, but the quesiton is, the textfiled have a `onTapOutside` func, which make if I tap outside of the textfiled, the soft keyboard will pops up

**Comment by Fintasys** [comment]
It's difficult to provide support without seeing code. Our examples try to cover basic behavior but the switch between keyboard and emoji-picker is not perfect and still can be improved in special circumstances. 
Let me know if I can help you further in this issue or the issue has been solved already 🙏

**Comment by arshnirmal** [comment]
I'm using state management here but you can also use setState to change isEmojiShowing value 
```
if (!store.isEmojiShowing) {
  await SystemChannels.textInput.invokeMethod('TextInput.hide');
}

store.isEmojiShowing = !store.isEmojiShowing;

if (store.isEmojiShowing) {
  if (focusNode.hasFocus) {
    focusNode.unfocus();
  }
} else {
  await SystemChannels.textInput.invokeMethod('TextInput.show');
  focusNode.requestFocus();
}
```

**Comment by Fintasys** [comment]
I assume this issue has been solved? Please open a new issue if there is an issue still remaining 🙏

**Comment by kevin4dhd** [comment]
Any solution?

**Comment by Fintasys** [comment]
Please create a new issue with details if you have similar problem 🙏
