### ISSUE TITLE
Replacing items in recent list

### ISSUE THREAD

**Issue by PhantomRay** [Fintasys/emoji_picker_flutter#135]
hi there
It seems that once the recent list reaches the limit, newly used emoji will only replace the last item, not others.

When updating the recent history, can we:
* remove the least used item
* sort the list by time `desc`

**Comment by Fintasys** [comment]
I'm aware of the issue and behavior. It's on my Todo list, but haven't found time for it yet. If you interested to contribute let me know, then we can discuss the specs. Otherwise please be a bit more patient 🙇
