### ISSUE TITLE
All emojis are black and white from the last upgrade.

### ISSUE THREAD

**Issue by ProfiroiuMihai** [Fintasys/emoji_picker_flutter#136]
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/44637696/c4e0d572-3520-497e-a746-0a23d8311902)

**Comment by Fintasys** [comment]
@ProfiroiuMihai Are you sure you are not using a custom-font?

**Comment by Fintasys** [comment]
Make sure to use the correct custom font. The current example had black and white custom font. I will update it now to be colored by default.

Replace 
```
emojiTextStyle: GoogleFonts.notoEmoji(color: Colors.black),
```
with:
```
emojiTextStyle: GoogleFonts.notoColorEmoji(),
```

**Comment by marcuscorreasmash** [comment]
yeah, if to force emojiTextStyle: GoogleFonts.notoColorEmoji(), him open colored list. But i'm use font roboto into my project so when i'm paste the emoji into input Text, him showing black and white. This problem just show in desktop chrome

If i'm open website in my mobile, all works!

desktop chrome:
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/123556973/8776ea1a-253d-4549-8313-4b43ea4c1404)

mobile chrome:
![WhatsApp Image 2023-06-13 at 17 26 51](https://github.com/Fintasys/emoji_picker_flutter/assets/123556973/2e22b9e1-9791-4f3a-b261-601d88a759cd)

**Comment by DyNamite-TNT-1** [comment]
I added notoColorEmoji Font inside EmojiPicker class.
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/104590526/ff481e7f-4fcf-4754-9fcc-f36f16917049)
And it worked.
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/104590526/4e4727bc-7866-44a0-a463-aa21fd2d4f72)
I use textfield like your example to display emoji, but it shows black and white emoji. I fixed it by using notoColorEmoji Font again into textStyle of textfield. There's a problem is space too large.
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/104590526/34f51638-f673-4aa2-aa6f-7ec6ce153da9)
So have you another Font for fix this?
Sorry about my english if it make u confuse when read this. I try to be better! Thank you!

**Comment by marcuscorreasmash** [comment]
I managed to solve for flutter web by updating the engine Initializer.initializeEngine line passing parameter **useColorEmoji: true**

example: engineInitializer.initializeEngine({ useColorEmoji: true });

With it, it was not necessary to pass any other parameters in the package.

If you want to check it out, you can access our gift cards website developed in flutter: https://loja.smash.gifts/

tks

**Comment by HoangHieuHBR** [comment]
I have same bug but with Desktop app. When I using GoogleFonts.notoColorEmoji() - All emojis will disappear. But when I change to GoogleFonts.notoEmoji(color: Colors.black) - all emojis are back but it just baclk and white

With GoogleFonts.notoColorEmoji() :
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/121141914/a9be0515-6ae3-4946-94ca-52be7ef410ce)

With GoogleFonts.notoEmoji(color: Colors.black)

![image](https://github.com/Fintasys/emoji_picker_flutter/assets/121141914/4d032059-d666-48b8-8db2-10f4921f0829)

Any solution to solve this.
