### ISSUE TITLE
Feature request: What if you can add iOS emoji's instead of only Android ones?

### ISSUE THREAD

**Issue by imgarvish** [Fintasys/emoji_picker_flutter#141]
See this [article](https://blog.logrocket.com/standardizing-emoji-displays-across-android-and-ios-apps/#standardizing-emoji-display), for example. They've used iOS emojis on the Android platform with the help of the Android package.

Would love to see this in feature updates. Thanks ;)

**Comment by Fintasys** [comment]
Interesting, but I think Android users won't enjoy suddenly iOS emojis that they aren't used with 🤔 Currently I'm not planing to make this possible. If you need this I would rather suggest to fork the repository and apply those changes directly.
