### ISSUE TITLE
some of emoji show two(??) like  1️⃣2️⃣3️⃣ ---- 9, in ios, how to handle it, and if  starts with 1️⃣, then all the emoji show ???????

### ISSUE THREAD

**Issue by yangmeng00124** [Fintasys/emoji_picker_flutter#142]

**Comment by Fintasys** [comment]
Thank you for reporting, I could find the issue and reason for it. Unfortunately is the fix not easy and I will take more time. 
In the meantime you might be able to fix appearance with
```
                    emojiTextStyle: const TextStyle(
                          fontFamilyFallback: ['Apple Color Emoji']),
```
But you need to add that everywhere where you use emoji, which could be troublesome.

**Comment by Fintasys** [comment]
There is actually a open PR to fix this in skia - but I guess this will take a while.
https://github.com/google/skia/pull/129
