### ISSUE TITLE
in web emoji not showing color only grey 

### ISSUE THREAD

**Issue by naveenpardeep** [Fintasys/emoji_picker_flutter#144]
i am trying to use this package but in web its showing grey color emoji 
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/42085829/a302dbc3-0de4-4c6c-825b-de568f130e80)

**Comment by Fintasys** [comment]
Similar issue exist already
https://github.com/Fintasys/emoji_picker_flutter/issues/136
