### ISSUE TITLE
如果只想要其中的某一列表情，怎么隐藏其他的？

### ISSUE THREAD

**Issue by Beixiaomi** [Fintasys/emoji_picker_flutter#145]

**Comment by Fintasys** [comment]
English please, then I might be able to help 🙏

**Comment by Beixiaomi** [comment]
If I only want one expression, how can I hide the others? The emojiSet property can be implemented, but clicking on a single emoji can cause page jitter. How can this be resolved?

**Comment by Fintasys** [comment]
@Beixiaomi Sorry for late reply.
```
 emojiSet: [defaultEmojiSet[0]],
 ```
 That would be my approach. I tested it and I couldn't find jitter. Please open a new issue if the issue causes any jitter with a video if possible 🙏
