### ISSUE TITLE
Abnormal emoj display, only occupying space

### ISSUE THREAD

**Issue by cxw18772827901** [Fintasys/emoji_picker_flutter#146]
Abnormal emoj display, only occupying space
![IMG_6951](https://github.com/Fintasys/emoji_picker_flutter/assets/14237362/39156abb-3512-49e1-b03d-593506ca835f)
May I ask what the reason is and how to solve it

**Comment by cxw18772827901** [comment]
Not all emoj displays have issues, only some of them will

**Comment by Fintasys** [comment]
Difficult to guess what's the issue here. Can you provide a test sample?

**Comment by EsteveAguilera** [comment]
I'm facing the same issue, using the latest version 1.6.1 (also on 1.5.2), and on different devices.

This is a screenshot of a Samsung Galaxy A32 5G using Android 12.

![Screenshot 2023-09-06 101736](https://github.com/Fintasys/emoji_picker_flutter/assets/6932449/a0cfff21-2a1f-4090-8293-c42651e54dee)

I've also tested on a Samsung Galaxy A52s and I've seen this:

![image](https://github.com/Fintasys/emoji_picker_flutter/assets/6932449/e46dbc35-7aab-4b3a-8dd3-6bd131993ba1)

**Comment by SungHyun22** [comment]
Same Issue Here

**Comment by Fintasys** [comment]
I assume this happens when the device doesn't support the emoji, especially on older devices. 
Solution is to use custom emoji font, please check readme to learn how to do it.
