### ISSUE TITLE
Issue with version control policy

### ISSUE THREAD

**Issue by MarsMan13** [Fintasys/emoji_picker_flutter#150]
First, thank you for providing a great Flutter library.

However, I think the version management method of this project is wrong.
Minor version changes should guarantee the operation of previous versions.
However, due to the 1.6.0 version update, Config's showRecentsTab is not available, so
Many projects that were based on the assumption that showRecentsTab is available have encountered problems.
(For example, _chatview_)

Please remember that minor versions guarantee previous versions, which is why we can use `^` in Flutter dependencies.

If I am wrong, please give me feedback.
Thank you.

**Comment by Fintasys** [comment]
@MarsMan13 Thanks for pointing this out. I will try to be more careful with versioning from now on 🙏
