### ISSUE TITLE
error：    flutter build web --web-renderer html。   Overlay.of(context)?.insert(_overlay!)

### ISSUE THREAD

**Issue by luoqiz** [Fintasys/emoji_picker_flutter#151]
flutter version：
![image](https://github.com/Fintasys/emoji_picker_flutter/assets/22161059/911dbd3f-9708-46fc-aa88-4a9b3fa37a3a)

emoji_picker_flutter： 1.6.1

![image](https://github.com/Fintasys/emoji_picker_flutter/assets/22161059/9de82f30-be0c-499a-8f1c-96812208093e)

**Comment by Fintasys** [comment]
Should be fixed in `1.6.2`. Please give it a try !
