### ISSUE TITLE
How to initalize emoji color in web

### ISSUE THREAD

**Issue by hardik-cloudus** [Fintasys/emoji_picker_flutter#152]
![Screenshot 2023-09-06 at 11 39 42 AM](https://github.com/Fintasys/emoji_picker_flutter/assets/127076025/ffbe398a-d185-4a06-bdf9-383dee173168)

**Comment by Fintasys** [comment]
@hardik-cloudus Please have a look at our example. How to add colored emoji you can read in the comments on the bottom.
https://github.com/Fintasys/emoji_picker_flutter/blob/master/example/lib/main_custom_font.dart
