### ISSUE TITLE
Bug: Getting internel sharedPreference error from emoji picker.

### ISSUE THREAD

**Issue by mdshihabuddinroky** [Fintasys/emoji_picker_flutter#154]
![Screenshot 2023-09-15 at 11 13 59 PM](https://github.com/Fintasys/emoji_picker_flutter/assets/99485727/8bed458a-1c05-4f1b-ad33-56f09db25767)
Getting error for emoji picker

**Comment by Fintasys** [comment]
@mdshihabuddinroky Could you resolve the issue? I can't reproduce the issue. If the issue is still present, please provide more information 🙏

**Comment by mdshihabuddinroky** [comment]
I think that was come for using flutter 3.13. Every time when new release come if I update to new release & do any internet request I face this issue

**Comment by Fintasys** [comment]
I don't think it's related to the package. Seems more like a general issue discussed here
https://stackoverflow.com/questions/72880037/unhandled-exception-platformexceptionchannel-error-unable-to-establish-connec

**Comment by Fintasys** [comment]
Please open another issue if it keeps happening again 🙏
