### ISSUE TITLE
ios build Definition of 'EmojiPickerFlutterPlugin' must be imported from module 'emoji_picker_flutter.Swift' before it is required

### ISSUE THREAD

**Issue by fuxianwei** [Fintasys/emoji_picker_flutter#158]
When I upgraded from 1.6.1 to 1.6.2, ios build reported an error as follows:
Could not build the precompiled application for the device.
Semantic Issue (Xcode): Duplicate interface definition for class 'EmojiPickerFlutterPlugin'
/Users/admin/Desktop/work/workspace/IM/selfim/chat_app/build/ios/Profile-iphoneos/emoji_picker_flutter/emoji_picker_flutter.framework/Headers/EmojiPickerFlutterPlugin.h:2:0

Modules Issue (Xcode): Definition of 'EmojiPickerFlutterPlugin' must be imported from module 'emoji_picker_flutter.Swift' before it is required
/Users/admin/Desktop/work/workspace/IM/selfim/chat_app/ios/Runner/GeneratedPluginRegistrant.m:232:3

**Comment by Fintasys** [comment]
Thank you for reporting, I will check it 🙏

**Comment by Fintasys** [comment]
Can you try `flutter clean` ? I faced no issue compiling the example for iOS 🤔
