### ISSUE TITLE
Frowning Face - missing the matching emoji in the picker

### ISSUE THREAD

**Issue by tboeve-topicus** [Fintasys/emoji_picker_flutter#163]
The default emoji-set seems to be missing the correct emoji in default_emojiset.dart resulting in this being displayed incorrectly in the date picker - 
(version 1.6.2)

Got this:
Emoji('☹', 'Frowning Face'),

Expecting this:
Emoji('☹️', 'Frowning Face'),

**Comment by Fintasys** [comment]
It's unfortunately depends on the device or font. There are some articles about it. Even if it is displayed here the second time correctly, if I copy paste it into the code there is no diff 😢 
https://www.androidcentral.com/frowny-face-emoji-android-crapshoot-and-it-has-change
https://stackoverflow.com/questions/70705389/chrome-does-not-render-frowning-face-emoji-in-color-when-using-sans-serif-font-f

**Comment by Fintasys** [comment]
It's unfortunately depends on the device, software or font. There are some articles about it. Even if it is displayed here the second time correctly, if I copy paste it into the code there is no difference 😢  Here are some links about it, I’m not sure why this is still an issue…
https://www.androidcentral.com/frowny-face-emoji-android-crapshoot-and-it-has-change
https://stackoverflow.com/questions/70705389/chrome-does-not-render-frowning-face-emoji-in-color-when-using-sans-serif-font-f
<img width="399" alt="Screen Shot 2023-10-25 at 23 06 47" src="https://github.com/Fintasys/emoji_picker_flutter/assets/11667234/b72fd917-cc9f-4e11-8625-cab6975a0291">
<img width="179" alt="Screen Shot 2023-10-25 at 23 07 50" src="https://github.com/Fintasys/emoji_picker_flutter/assets/11667234/56081a48-f73f-441b-aa65-8f511351f87a">

**Comment by Fintasys** [comment]
`Frowning Face` is unfortunately not correctly displayed on even recent devices and android versions. Also it is not recognized as unsupported emoji. If you want to support the emoji you can use a custom emoji font. Please check the ReadMe to learn how to do it. I think there is no better way unless Google gonna fix it directly in Android.
