### ISSUE TITLE
Jack-O-Lantern emoji is missing

### ISSUE THREAD

**Issue by The-Redhat** [Fintasys/emoji_picker_flutter#164]
I can't find the pumpkin emoji in this list: https://github.com/Fintasys/emoji_picker_flutter/blob/master/lib/src/default_emoji_set.dart

https://emojipedia.org/jack-o-lantern#technical

**Comment by Fintasys** [comment]
Thanks for reporting ! What a important emoji to miss at this time of the year. I will add it soon 🙏

**Comment by Fintasys** [comment]
Fixed in `1.6.3`
