### ISSUE TITLE
U+2639 Frowning Face Emoji renders incorrectly on iOS

### ISSUE THREAD

**Issue by emesterhazy** [Fintasys/emoji_picker_flutter#170]
The [frowning face](https://github.com/Fintasys/emoji_picker_flutter/blob/0a206b60e6b6a431b886081b94713ab8547d1b97/lib/src/default_emoji_set.dart#L81C12-L81C13) emoji does not render correctly on iOS, even though iOS supports it.

<img width="396" alt="Screenshot 2023-11-24 at 10 51 37" src="https://github.com/Fintasys/emoji_picker_flutter/assets/26512665/92376e37-d224-42ea-87ca-712b7b45df4c">

Another dev reported this issues ~2 years ago, but it was closed because technically users can override the default fonts in order to get the emoji to work.

In my opinion, the emoji picker should work without the user setting a custom font. On iOS we can fix this by using `Apple Color Emoji` as the default font when the user doesn't set a custom font.

<img width="399" alt="Screenshot 2023-11-24 at 11 26 34" src="https://github.com/Fintasys/emoji_picker_flutter/assets/26512665/52ce724a-686f-4713-9c0a-55158eef19fd">

**Comment by Fintasys** [comment]
Thank you @emesterhazy for your great contributions ! Give me few days time to check and validate the changes in your PR 🙏
