### ISSUE TITLE
Backspace drag/long-press doesn't execute onBackspacePressed continuously

### ISSUE THREAD

**Issue by vedasjad** [Fintasys/emoji_picker_flutter#177]
If deleting one character onBackspacePressed, then onLongPress or Drag it must keep deleting characters until empty.

**Comment by Fintasys** [comment]
Sorry can you explain the issue more detailed? I wasn't able to understand the exact issue

**Comment by starfreck** [comment]
> If deleting one character onBackspacePressed, then onLongPress or Drag it must keep deleting characters until empty.

+1

**Comment by Fintasys** [comment]
Available since version 1.6.4
