### ISSUE TITLE
iOS lag issue with Google Fonts

### ISSUE THREAD

**Issue by Fintasys** [Fintasys/emoji_picker_flutter#185]
I've noticed a weird lag on iOS when I was developing for version 2.0. Unfortunately this issue already exists in current version 1.6.3 and seems to be related with GoogleFonts. When I remove GoogleFonts it works perfectly fine. I tried to improve the Google Fonts setup, making sure the font is loaded before the EmojiPicker is displayed, but I couldn't resolve the issue 🤔 
I could only test it on simulator for now and not physical device. Hopefully the issue exists only on my computer 🙏 

Reproducible using `main_custom_font.dart`  [example](https://github.com/Fintasys/emoji_picker_flutter/blob/master/example/lib/main_custom_font.dart).
or current version 2.0 [WhatsApp example](https://github.com/Fintasys/emoji_picker_flutter/blob/version-2.0/example/lib/main_whatsapp.dart)

Video:

https://github.com/Fintasys/emoji_picker_flutter/assets/11667234/633b6fb8-cc0c-4f56-82b2-31b668380e6a

**Comment by Fintasys** [comment]
@emesterhazy @LostInDarkMath @yendacoder You guys contributed a lot in the past, If you have time, I would appreciate if you could check if the issue is reproducible and what could cause it. 🙇

**Comment by LostInDarkMath** [comment]
Hi @Fintasys 
unfortunately I cannot test this because I do not have any Apple device.

**Comment by yendacoder** [comment]
Hi @Fintasys 
It is reproducible on simulator, but on a device it's not bad at all. In debug mode there's a tiny lag, way less than on emulator. In release mode it's perfectly fine, as for me, so I wouldn't bother spending too much time on this. Maybe someone wants to check the performance trace out of curiosity, but my iOS setup is too cumbersome for this.

https://github.com/Fintasys/emoji_picker_flutter/assets/91149096/3c971ef6-aa89-4452-a790-79e227e7ed56

**Comment by Fintasys** [comment]
@yendacoder thank you, I appreciate your quick help to check the issue! That's really relieving 🙏In a few days I have access again to a physical device and will double check it 👍

**Comment by Fintasys** [comment]
Issue seems not exist in release mode or physical device.
