### ISSUE TITLE
ScrollController not attached to any scroll views. 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 157 pos 12: '_positions.isNotEmpty'

### ISSUE THREAD

**Issue by ankittiwari25** [Fintasys/emoji_picker_flutter#196]
in initState method you are adding addListener of textEditingController and and passing _scrollToCursorAfterTextChange method at that time you are using animateTo method.At that time it showing this error.
<img width="1081" alt="Screenshot 2024-03-21 at 18 06 28" src="https://github.com/Fintasys/emoji_picker_flutter/assets/54878509/adc85515-7841-42ca-ad37-470a7a57f87d">

**Comment by ankittiwari25** [comment]
Just update this method to below code it will work fine

**Comment by Fintasys** [comment]
Thanks for reporting, I fixed the issue with version `2.1.1` which I just have released 🙏

**Comment by ankittiwari25** [comment]
@Fintasys thanks buddy for fixing this issue
