### ISSUE TITLE
EmojiView Scroll Performance

### ISSUE THREAD

**Issue by dhikshithrm** [Fintasys/emoji_picker_flutter#199]
Thanks for making this awesome package, it already has fast loading than the other ones available on pub, but i noticed frame drops while scrolling down through emojis in a category, it's not a deal breaker, just wanted to let you know.

**Comment by Fintasys** [comment]
Thanks, I glad you like it.
About the scrolling performance, have you tried it in debug or production? The performance in production is normally significant better than debug. Let me know!

**Comment by Fintasys** [comment]
Please create a new issue when this becomes an issue again
