### ISSUE TITLE
Support Web platform

### ISSUE THREAD

**Issue by Fintasys** [Fintasys/emoji_picker_flutter#2]
Every platform seems not support all of the emoji and it's difficult to filter them. I'm looking for ideas for filtering methods beside doing it manually.

**Comment by gooplancton** [comment]
I'd say you can just depend on this https://pub.dev/packages/universal_platform

**Comment by JLuisRojas** [comment]
@Fintasys  Do you have any advancements for web and MacOS support? Maybe i can help you

**Comment by Fintasys** [comment]
@JLuisRojas Thanks for bringing this up again ! I quickly looked into it and seems MacOS and Web (when used with html-render) actually works quite well. Give me a few days to test it more carefully also on other OS than MacOS in case of Web support. If it looks fine I gonna release it soon 👍

**Comment by JLuisRojas** [comment]
Perfect! Thanks

**Comment by aliasgarlabs** [comment]
> @JLuisRojas Thanks for bringing this up again ! I quickly looked into it and seems MacOS and Web (when used with html-render) actually works quite well. Give me a few days to test it more carefully also on other OS than MacOS in case of Web support. If it looks fine I gonna release it soon 👍

Cheering for you mate! 💯 Also IMHO, we can prioritize just the web support as Flutter Web is a major shareholder compared to macOS and other OSes. Thanks!

**Comment by telostia** [comment]
It would be good to add Web support! Any progress on the web if I may ask?

**Comment by Fintasys** [comment]
@telostia Unfortunately not, there has been also no progress from flutter's side to address existing issues. Eventuelly I could add custom font support so that people could optionally add the NotoColorEmoji font themselves 🤔 will think about it.

**Comment by marcusgregory** [comment]
> @JLuisRojas I was looking more closely into web the other day and I still see lot of issues. Most troublesome is that some emoji's can't be displayed and we can't just filter them like we do on Android. Solution would be to add NotoColorEmoji font to the project but it would add like 10 mb to the app size, which I would like not to do if possible. If you have any other ideas for workaround let me know. I'm keep watching serval flutter issues for the moment and see if something changes.

I was researching this today and found a comment:
https://stackoverflow.com/questions/52366470/how-to-check-if-an-emoji-is-supported-by-any-device-or-not

Basically it says that if you draw an emoji using the canvas and compare it to a character that you know will not be compatible (\u1fff) you can test if the emoji will be visible to the user or not.

Does anyone know how to implement this in Flutter?

**Comment by SmithZachary** [comment]
Following, trying to implement this package into an upcoming app and am trying to figure out the web side of it.

**Comment by thorito** [comment]
Any news with web support?

**Comment by Fintasys** [comment]
@thorito @telostia @aliasgarlabs @JLuisRojas 
I made a new draft PR to add Web support. Thx to recent changes from other contributors we have custom font support now and that should help with web support. I'm planing to release current master soon as new version and web support then again in another version to keep the possibility to go back in case something is not working well. But until now you can test it by using this

```
  emoji_picker_flutter:
    git:
      url: https://github.com/Fintasys/emoji_picker_flutter.git
      ref: Add-Web-Support-2
```

**Comment by thorito** [comment]
> @thorito @telostia @aliasgarlabs @JLuisRojas I made a new draft PR to add Web support. Thx to recent changes from other contributors we have custom font support now and that should help with web support. I'm planing to release current master soon as new version and web support then again in another version to keep the possibility to go back in case something is not working well. But until now you can test it by using this
> 
> ```
>   emoji_picker_flutter:
>     git:
>       url: https://github.com/Fintasys/emoji_picker_flutter.git
>       ref: Add-Web-Support-2
> ```


Great job, works fine.

Thank you very much

**Comment by Fintasys** [comment]
Added support for Flutter Web with release `1.5.0`.
