### ISSUE TITLE
Because app depends on emoji_picker_flutter ^2.2.0 which doesn't match any versions, version solving failed.   You can try the following suggestion to make the pubspec resolve: * Consider downgrading your constraint on emoji_picker_flutter: flutter pub add emoji_picker_flutter:^2.1.1

### ISSUE THREAD

**Issue by yfming93** [Fintasys/emoji_picker_flutter#204]
/Users/mingo/flutter/bin/flutter pub get
Resolving dependencies...
Because app depends on emoji_picker_flutter ^2.2.0 which doesn't match any versions, version solving failed.

You can try the following suggestion to make the pubspec resolve:
\* Consider downgrading your constraint on emoji_picker_flutter: flutter pub add emoji_picker_flutter:^2.1.1
Process finished with exit code 1

**Comment by Fintasys** [comment]
Did you try to downgrade to 2.1.1 as the message states?
