### ISSUE TITLE
[Feature Request] Support customizing emoji style

### ISSUE THREAD

**Issue by nino-finch** [Fintasys/emoji_picker_flutter#21]
Hi loving what you build here! Just think that it'd be a great addition to the library if it also support different style of emoji e.g twemoji (for twitter), or allowing customization of how to render the emoji instead of the whole modal itself.

**Comment by Fintasys** [comment]
@nino-finch Thank you and glad you like it 🙇 Different Emoji's like twemoji seems to be difficult, at least I have no experience with that - feel free to contribute with an PR.
