### ISSUE TITLE
i getting some error

### ISSUE THREAD

**Issue by ismamilahi** [Fintasys/emoji_picker_flutter#214]
I getting some error how to fix this please tell me

here is error logs showing me

[{
	"resource": "#####/lib/widgets/reaction_pop_up/emoji_picker_widget.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_named_parameter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_named_parameter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The named parameter 'columns' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'columns'.",
	"source": "dart",
	"startLineNumber": 40,
	"startColumn": 17,
	"endLineNumber": 40,
	"endColumn": 24
},{
	"resource": "#####/lib/widgets/reaction_pop_up/emoji_picker_widget.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_named_parameter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_named_parameter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The named parameter 'emojiSizeMax' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'emojiSizeMax'.",
	"source": "dart",
	"startLineNumber": 41,
	"startColumn": 17,
	"endLineNumber": 41,
	"endColumn": 29
},{
	"resource": "######/lib/widgets/reaction_pop_up/emoji_picker_widget.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_named_parameter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_named_parameter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The named parameter 'bgColor' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'bgColor'.",
	"source": "dart",
	"startLineNumber": 42,
	"startColumn": 17,
	"endLineNumber": 42,
	"endColumn": 24
},{
	"resource": "######/lib/widgets/reaction_pop_up/emoji_picker_widget.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "undefined_named_parameter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_named_parameter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The named parameter 'recentsLimit' isn't defined.\nTry correcting the name to an existing named parameter's name, or defining a named parameter with the name 'recentsLimit'.",
	"source": "dart",
	"startLineNumber": 43,
	"startColumn": 17,
	"endLineNumber": 43,
	"endColumn": 29
},{
	"resource": "######/lib/widgets/reaction_pop_up/emoji_picker_widget.dart",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "unnecessary_import",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_import",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "The import of '../../utils/general_utils.dart' is unnecessary because all of the used elements are also provided by the import of '../../config.dart'.\nTry removing the import directive.",
	"source": "dart",
	"startLineNumber": 7,
	"startColumn": 8,
	"endLineNumber": 7,
	"endColumn": 40
}]

**Comment by Fintasys** [comment]
Have you tried `flutter clean`?

**Comment by Fintasys** [comment]
Close issue due to inactivity
