### ISSUE TITLE
version 3.1.0 is actually breaking

### ISSUE THREAD

**Issue by Peetee06** [Fintasys/emoji_picker_flutter#218]
I just updated the dependencies in my project and got compiler errors, because the `swapCategoryAndBottomBar` was removed. Therefore, the correct version should be `4.0.0` for this change. 

I'm positive replacing it with `viewOrderConfig` is a good design choice, but correctly versioning helps users be confident when updating dependencies.

**Comment by Fintasys** [comment]
Yes right, sorry my mistake 🙏 Will try to be more careful next time. Thx for noticing 🙇

**Comment by Peetee06** [comment]
No hard feelings! Thanks for building and improving this. Using it in my guided journaling app "emotely" 👍
