### ISSUE TITLE
Parse Issue (Xcode): Module 'emoji_picker_flutter' not found

### ISSUE THREAD

**Issue by armagangok** [Fintasys/emoji_picker_flutter#226]
Parse Issue (Xcode): Module 'emoji_picker_flutter' not found
/Users/armagangok/Documents/AppSweat/habitrise/ios/Runner/GeneratedPluginRegistrant.m:11:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.

**Comment by Fintasys** [comment]
Have you tried `flutter clean` and `pod update`?

**Comment by armagangok** [comment]
Hello, I removed the package, I guess it's better to close the issue (:
