### ISSUE TITLE
The view when scrolling very slow

### ISSUE THREAD

**Issue by wijamad** [Fintasys/emoji_picker_flutter#23]
I dont know,Is just me or another people also.I think when scrolling or change catagory very slow.Anyone can help me?

**Comment by Fintasys** [comment]
@wijamad Hey ! Could you provide some code / video so we can understand your problem better?

**Comment by wijamad** [comment]
https://youtu.be/iUig0ErnRho i dont know how upload video in youtube. When i change catagory or scrolling emoji its slow but i open whatsapp emoji its'nt slow

**Comment by Fintasys** [comment]
Seems something in your code might not be correct. Would you able to share it  here ?

**Comment by wijamad** [comment]
sorry is my false,i open app in real device and try app not debungging but after debbuging is smoot,i will close it,sorry
