### ISSUE TITLE
Frowned emoji not loaded correctly

### ISSUE THREAD

**Issue by ultrasandbox** [Fintasys/emoji_picker_flutter#24]
Hello,

 I am having a problem with the following frowned emoji:
![Screenshot_1631466929](https://user-images.githubusercontent.com/83548376/132999388-ec834e52-f00a-4e8a-946f-0aefd84bf104.png)

When I save it the first time, everything is fine. But when I close the app and open again, it is not rendered correctly (displays black and white emoji). Please help on this issue. Thank you!

![Screenshot_1631472534](https://user-images.githubusercontent.com/83548376/132999390-aea93da5-c4a2-4672-8cb1-2765a27ebe24.png)
![Screenshot_1631472598](https://user-images.githubusercontent.com/83548376/132999391-04df64cc-8f8e-4a59-9559-fe1d755869b6.png)

![240957786_1038310930251894_6037322601503048516_n](https://user-images.githubusercontent.com/83548376/133018963-cc787797-01a9-4af3-a241-467a7de159a8.jpg)

The frowned emoji next to boat will be broken if it is initially used somewhere when the app opens. If it is not used anywhere initially, then it seems to show correctly.

![240746536_558674565472576_5511491939658074663_n](https://user-images.githubusercontent.com/83548376/133018955-4bf7d4fb-7429-401f-b6ef-e189b7d22d4f.jpg)

 The black and white bug appears on both iOS and Android

**Comment by Fintasys** [comment]
@ultrasandbox Hey ! Thanks for your feedback ! I'm following a similar/same issue on the Flutter repository. Could you check if the mentioned work around works for you? https://github.com/flutter/flutter/issues/82785

**Comment by ultrasandbox** [comment]
Thanks! I used Apple Color Emoji & Noto Color emoji as font family now they are showing up
