### ISSUE TITLE
On every setState() the emoji picker is redrawn

### ISSUE THREAD

**Issue by Zverik** [Fintasys/emoji_picker_flutter#27]
I have a regular text field alonside the emoji picker. It has a listener to update the state every time a key is pressed: `onChanged: (value) { setState(() {...}); }`.

The issue is, on every call to `setState()` anywhere inside the containing widget, the emoji picker is redrawn from scratch: the tab is changed to the default one, the list of emoji is cleared and then slowly appears, scroll state is reset too.

Is there a way to disable or fix that?

**Comment by asnbd** [comment]
> 
> 
> I have a regular text field alonside the emoji picker. It has a listener to update the state every time a key is pressed: `onChanged: (value) { setState(() {...}); }`.
> 
> The issue is, on every call to `setState()` anywhere inside the containing widget, the emoji picker is redrawn from scratch: the tab is changed to the default one, the list of emoji is cleared and then slowly appears, scroll state is reset too.
> 
> Is there a way to disable or fix that?

I'm also facing the same issue only when I set custom config.

**Comment by Zverik** [comment]
Thanks for the tip! Your PR should indeed fix this. Also in the current version it can be resolved by adding `const` modifier to the config.
