### ISSUE TITLE
Emojis does not load on android

### ISSUE THREAD

**Issue by hiteshgarg002** [Fintasys/emoji_picker_flutter#3]
Emojis are being shown on iOS but when I am trying to run it on android, then the emojis does not load.
Following is the error being shown in console.

/flutter ( 9064): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..260: 261
E/flutter ( 9064): #0      List.[] (dart:core-patch/growable_array.dart:254:60)
E/flutter ( 9064): #1      _EmojiPickerState._getPlatformAvailableEmoji
package:emoji_picker_flutter/emoji_picker_flutter.dart:212
E/flutter ( 9064): <asynchronous suspension>
E/flutter ( 9064): #2      _EmojiPickerState._getAvailableEmojis
package:emoji_picker_flutter/emoji_picker_flutter.dart:186
E/flutter ( 9064): <asynchronous suspension>
E/flutter ( 9064): #3      _EmojiPickerState._updateEmojis
package:emoji_picker_flutter/emoji_picker_flutter.dart:173
E/flutter ( 9064): <asynchronous suspension>
E/flutter ( 9064): #4      _EmojiPickerState.build.<anonymous closure> (package:emoji_picker_flutter/emoji_picker_flutter.dart)
package:emoji_picker_flutter/emoji_picker_flutter.dart:1

**Comment by Fintasys** [comment]
@hiteshgarg002 Ah thanks for reporting, I found the issue. Will fix it tomorrow 👍

**Comment by Fintasys** [comment]
Fixed in version `1.0.2`. Please have a try and let me know if it works for you now 🙇

**Comment by hiteshgarg002** [comment]
@Fintasys  Thanks its working now!!
