### ISSUE TITLE
Activity category removed?

### ISSUE THREAD

**Issue by dna-f** [Fintasys/emoji_picker_flutter#33]
Hi, it seems that the activity category has been removed with the following commit
https://github.com/Fintasys/emoji_picker_flutter/commit/1f2c9882bc6143b46aa8e9c0aef1cfb8e6d9f365#diff-fdfda11d45a50edbf3fafe7280bbae036f0a03fc10094e622b04e3215ad27989

Was that wanted?
Thanks

**Comment by maboutik-dev** [comment]
I confirmed, why this category is missing ?

**Comment by Fintasys** [comment]
It was removed by mistake but added back - I just released `v.1.0.8`
Thank you for reporting 🙇

**Comment by dna-f** [comment]
You are great!
Thanks
