### ISSUE TITLE
emoji repeat display

### ISSUE THREAD

**Issue by wuhuaqing** [Fintasys/emoji_picker_flutter#36]
hello,my widget has this problem

![image](https://user-images.githubusercontent.com/9549867/147376497-4b3207bc-97ea-48c7-a1d6-a5b9d35753fa.png)

**Comment by wuhuaqing** [comment]
verson:emoji_picker_flutter: 1.0.8

**Comment by wuhuaqing** [comment]
version:emoji_picker_flutter: 1.0.8

**Comment by Fintasys** [comment]
@wuhuaqing Thank you for reporting ! I can confirm that there has be duplicates 🙏 I gonna fix them 👍

**Comment by Fintasys** [comment]
Just to mention, even tho I fixed the genders, `Man Superhero` and `Female Superhero` as well as `Man Supervillain`  and `Female Supervillain` look very similar on Android devices by default.

**Comment by wuhuaqing** [comment]
Thank you !!!
