### ISSUE TITLE
There is a bug in the new version 1.1.0

### ISSUE THREAD

**Issue by cnkygmr** [Fintasys/emoji_picker_flutter#48]
`I/flutter (21183): type 'Null' is not a subtype of type 'bool' in type cast
I/flutter (21183): #0      Emoji.fromJson (package:emoji_picker_flutter/src/emoji.dart:30:40)
I/flutter (21183): #1      RecentEmoji.fromJson (package:emoji_picker_flutter/src/recent_emoji.dart:20:13)
I/flutter (21183): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
I/flutter (21183): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
I/flutter (21183): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
I/flutter (21183): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
I/flutter (21183): #6      new List.of (dart:core-patch/array_patch.dart:51:28)
I/flutter (21183): #7      ListIterable.toList (dart:_internal/iterable.dart:213:44)
I/flutter (21183): #8      EmojiPickerInternalUtils.getRecentEmojis (package:emoji_picker_flutter/src/emoji_picker_internal_utils.dart:136:56)
I/flutter (21183): <asynchronous suspension>
I/flutter (21183): #9      EmojiPickerState._updateEmojis (package:emoji_picker_flutter/src/emoji_picker.dart:214:22)
I/flutter (21183): <asynchronous suspension>
I/flutter (21183): ----------------------------------------------------
`

**Comment by Fintasys** [comment]
@cnkygmr Thank you for reporting. Can you tell me the steps that led to this error? I assumed it might happen when upgrading from `1.0.8` to `1.1.0` but I can't reproduce it.

**Comment by Fintasys** [comment]
Can you let me know if my changes above fixes your issues?
```
  emoji_picker_flutter:
    git:
      url: https://github.com/Fintasys/emoji_picker_flutter.git
      ref: master
```

**Comment by cnkygmr** [comment]
@Fintasys I tried like this, no problem, it worked

> Can you let me know if my changes above fixes your issues?
> 
> ```
>   emoji_picker_flutter:
>     git:
>       url: https://github.com/Fintasys/emoji_picker_flutter.git
>       ref: master
> ```

@Fintasys I tried like this, no problem, it worked

**Comment by Fintasys** [comment]
Thank you for checking, will release it as `1.1.1` 👍
