### ISSUE TITLE
Skin tone overlay

### ISSUE THREAD

**Issue by dokenedgar** [Fintasys/emoji_picker_flutter#51]
The skintone overlay doesn't close with the rest of the emojis on dismissing the emoji picker or when an empty space in the list of emojies, i.e. when none of the displayed skin tones is tapped.

Tested it on both Android and iOS.
 
![Screenshot_1644434067](https://user-images.githubusercontent.com/25203963/153273555-e0784f09-0157-4f80-a6f9-88998f02157a.png)
![Screenshot_1644433732](https://user-images.githubusercontent.com/25203963/153273564-ef370225-c64b-4cc1-8d1b-7b5c0c13e4ec.png)

**Comment by dokenedgar** [comment]
Forked and fixed this, as I'm using it in a project. WIll do a PR if the behavior is needed, can be discarded if what I experienced is an isolated case.

**Comment by Fintasys** [comment]
Thank you very much for fixing this. I've also noticed that sometimes it wasn't removed 🙏  I've left a comment on your PR, please have a look!

**Comment by Fintasys** [comment]
I've merged it, thanks again ! If you want to use it right away you can use. Otherwise I will release a new version soon after I've took a look on 2 other issues. 
```
  emoji_picker_flutter:
    git:
      url: https://github.com/Fintasys/emoji_picker_flutter.git
      ref: master
```
