### ISSUE TITLE
How can I get unify code from emoji?

### ISSUE THREAD

**Issue by tzthantzin** [Fintasys/emoji_picker_flutter#57]
How can I get unify code from emoji?
I click 'grinning face', its unified code is 1F600.
How can I get that value from emoji picker?
https://unicode.org/emoji/charts-13.0/full-emoji-list.html

Thank you very much

**Comment by Fintasys** [comment]
A emoji consists of runes. Simple emoji's like 'grinning face' only have 1 rune, if you add skin color etc they will have multiple runes. `1F600` is Hex which is nothing else like a number. So in dart the runes are from type `Integer` and you can easily format them to hex.

```
EmojiPicker(
                      onEmojiSelected: (Category category, Emoji emoji) {
                        emoji.emoji.runes.forEach((element) {
                          print(element.toRadixString(16));
                        });
                      }
                      ...
)
```
I hope that helps you !

**Comment by tzthantzin** [comment]
Thank you very much @Fintasys .
It is working 
Thank you very much 🙏

**Comment by EmmanyTaskWorld** [comment]
When i select country flag..using `emoji.emoji.runes.forEach((element) {
                print(element.toRadixString(16)); // 1F600
            });` doesn't seem to work as country flag emoji unicode should be in this form (U+1F1E6-1F1EE)
