### ISSUE TITLE
Emoji not sent as part of message

### ISSUE THREAD

**Issue by AnubhavChaubey1** [Fintasys/emoji_picker_flutter#59]
![Screenshot_1646361522](https://user-images.githubusercontent.com/83594567/156688722-92e0f7d9-3087-43ce-af93-a630e4c12aeb.png)

Hello team,
I'm facing a issue with your package. I am creating a message application where I use your package for sharing emojis. The issue that I'm facing is that, whenever I try to share only emoji as a message, I've to add a space as a suffix to make it shareable. Unless, I add a space, the message is not shared.

Example below is the code sample that I'm using:

 Widget buildSticker() {
    return Offstage(
      offstage: !emojiShowing,
      child: SizedBox(
        height: 250,
        child: EmojiPicker(
            onEmojiSelected: (Category category, Emoji emoji) {
              _onEmojiSelected(emoji);
            },
            onBackspacePressed: _onBackspacePressed,
            config: Config(
                columns: 7,
                // Issue: https://github.com/flutter/flutter/issues/28894
                emojiSizeMax: 32 * (Platform.isIOS ? 1.0 : 0.7),
                verticalSpacing: 0,
                horizontalSpacing: 0,
                initCategory: Category.RECENT,
                bgColor: const Color(0xFFF2F2F2),
                indicatorColor: Colors.blue,
                iconColor: Colors.grey,
                iconColorSelected: Colors.blue,
                enableSkinTones: true,
                progressIndicatorColor: Colors.blue,
                backspaceColor: Colors.blue,
                showRecentsTab: true,
                recentsLimit: 28,
                noRecentsText: 'No Recents',
                noRecentsStyle: TextStyle(
                  fontSize: 20,
                  color: Colors.black26,
                  fontFamily: ChatTheme.appFont,
                ),
                tabIndicatorAnimDuration: kTabScrollDuration,
                categoryIcons: const CategoryIcons(),
                buttonMode: ButtonMode.MATERIAL)),
      ),
    );
  }

 _onEmojiSelected(Emoji emoji) {
    _textController
      ..text += emoji.emoji
      ..selection = TextSelection.fromPosition(
          TextPosition(offset: _textController.text.length));
  }
![Screenshot_1646361906](https://user-images.githubusercontent.com/83594567/156689304-e905674f-ba3d-4db0-b91f-afd2bee2ffd2.png)
![Screenshot_1646361909](https://user-images.githubusercontent.com/83594567/156689311-21c21f9a-e30e-4ac1-9a38-7036401d7015.png)

**Comment by AnubhavChaubey1** [comment]
Solved by a small hack of seeting the active state of the textcontroller. Thank you

**Comment by sridhar562345** [comment]
> active state

@AnubhavChaubey1 can you elaborate the answer?
