### ISSUE TITLE
Export Emoji class from emoji.dart

### ISSUE THREAD

**Issue by dfdgsdfg** [Fintasys/emoji_picker_flutter#7]
Is there any reason you wouldn't export Emoji class?

`onEmojiSelected` has Catagory and Emoji class but Emoji class didn't expose.

**Comment by Fintasys** [comment]
Thanks for reporting this bug. I gonna look into it !

**Comment by Fintasys** [comment]
@dfdgsdfg I fixed it, please let me know if it works for you :)
