### ISSUE TITLE
Emoji picker often refresh.

### ISSUE THREAD

**Issue by vernalclareai** [Fintasys/emoji_picker_flutter#81]
Version: 1.3.0

-issue: It is refreshed on setState function automatically.
So I can not choose the emojis properly.

-Expected
It should not be refreshed after rendering once.

**Comment by cnkygmr** [comment]
same problem If you don't put config, it works fine because there is const, if you enter config variables manually, it is constantly renewed

**Comment by Junesui** [comment]
same issue

**Comment by PavelClaudiuStefan** [comment]
I had the same issue. In my case I fixed it by adding a key to the noRecents widget that replaced the default one

**Comment by Fintasys** [comment]
@vernalclareai @cnkygmr @Junesui Please make sure that all custom Widgets used in `Config` are `const` Widgets! 
I will investigate a bit further to see if I can make it bullet proofed.
