### ISSUE TITLE
Support for a search function

### ISSUE THREAD

**Issue by aminedakhlii** [Fintasys/emoji_picker_flutter#83]
It would be appreciated if a search function (like the one supported in the native emoji picker of iOS) would be implemented and embedded into the package. 
Example scenario : instead of spending time searching for the 😢 emoji It would be better if users could just type sad into a the search box and the related emojis automatically appear

**Comment by Fintasys** [comment]
@aminedakhlii It should be possible to achieve it by using `final filterEmojiEntities = await EmojiPickerUtils().searchEmoji("face");` (see readme)
I will try to update the example soon with some sample implementation.

**Comment by Fintasys** [comment]
@aminedakhlii You can find search example now here
https://github.com/Fintasys/emoji_picker_flutter/blob/master/example/lib/main-search.dart
