### ISSUE TITLE
Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by Inihood1** [Fintasys/emoji_picker_flutter#84]
Any solution for this problem?

**Comment by PickPickPickPick** [comment]
在源码 WidgetsBinding.instance.addPostFrameCallback（）instance后面加上 ！， WidgetsBinding.instance!.addPostFrameCallback（）

**Comment by mjmon** [comment]
@Fintasys  Please check  [#85 ](https://github.com/Fintasys/emoji_picker_flutter/pull/85) fix for this

**Comment by LostInDarkMath** [comment]
Just upgrade to Flutter 3.0.0 or newer by running `flutter upgrade`.
