### ISSUE TITLE
Emoji List Mismatch (Koala)

### ISSUE THREAD

**Issue by nathandud** [Fintasys/emoji_picker_flutter#86]
The Koala emoji 🐨 is mismatched with its description in the `Category.ANIMALS` map in `emoji_lists.dart`. The text description is correctly positioned at 67 between Bat 🦇 and Kangaroo 🦘. However, it is positioned at 9 in the list of emojis between Panda Face 🐼 and 🐯. 

This does not affect the user experience on the base emoji picker, but it adversely affects `EmojiPickerUtils.searchEmoji` for animals positioned between 9 and 67. 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/8878365/177700252-c2f2f917-9bd6-4374-86d7-5e77a87c07dd.png">

<img width="65" alt="image" src="https://user-images.githubusercontent.com/8878365/177700399-28d38ac0-a1d8-43ad-ba6d-d39a289ca634.png">

**Comment by Fintasys** [comment]
Thank you for your contribution 🙇
