### ISSUE TITLE
Linux platform support

### ISSUE THREAD

**Issue by 12people** [Fintasys/emoji_picker_flutter#92]
It'd be great if the emoji picker could also support the Linux platform.

There is a [native GTK chooser](https://docs.w3cub.com/gtk~4.0/gtkemojichooser) that could be used, but a Flutter-based emoji picker would be alright as well.

**Comment by Fintasys** [comment]
Hey @12people let me check if we can add support for Linux. I haven't checked if there would be anything that would block it.
