### ISSUE TITLE
Provide UI elements that can be used to build search results

### ISSUE THREAD

**Issue by yendacoder** [Fintasys/emoji_picker_flutter#95]
Related to #94: even though it is possible to build a search feature completely outside of the picker itself, doing so requires re-implementation of some UI elements of the library. Would be handy to have at least reusable grid cell widgets available to the host app, preferably with skin tone picker overlay.

**Comment by Fintasys** [comment]
@yendacoder thanks for creating an issue for your improvement suggestion. I like the idea and can't think of any issues bases on this change. Would be great if you could provide a PR for that if you have time 🙏
