### ISSUE TITLE
hide emoji picker

### ISSUE THREAD

**Issue by Junesui** [Fintasys/emoji_picker_flutter#99]
I want to
<1>hide the emoji picker when opening the keyboard
<2>hide the emoji picker when clicked outside the emoji picker (containing the clickable button). 

Is there a sample code like this?

**Comment by Fintasys** [comment]
I would recommend you checking out https://pub.dev/packages/flutter_keyboard_visibility
I was working on improving the examples by using it but due to recent breaking changes I will need more time to apply the changes again.

**Comment by Junesui** [comment]
hi Fintasys
thanks
